# Generated by Django 3.1.1 on 2020-09-14 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0002_auto_20200909_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamInLeague',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
