# Generated by Django 3.1.1 on 2020-09-14 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0003_teaminleague'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leagues',
            name='leagur_id',
        ),
        migrations.RemoveField(
            model_name='leagues',
            name='title',
        ),
        migrations.AddField(
            model_name='leagues',
            name='country_id',
            field=models.IntegerField(blank=True, default=20),
        ),
        migrations.AddField(
            model_name='leagues',
            name='country_logo',
            field=models.CharField(blank=True, max_length=90),
        ),
        migrations.AddField(
            model_name='leagues',
            name='country_name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='leagues',
            name='league_id',
            field=models.IntegerField(blank=True, default=20),
        ),
        migrations.AddField(
            model_name='leagues',
            name='league_logo',
            field=models.CharField(blank=True, max_length=90),
        ),
        migrations.AddField(
            model_name='leagues',
            name='league_season',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
