# Generated by Django 3.1.1 on 2020-09-15 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0004_auto_20200914_1001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leagues',
            name='country_logo',
        ),
    ]
