# Generated by Django 3.1.1 on 2020-09-15 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0005_remove_leagues_country_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leagues',
            name='country_name',
        ),
    ]
