# Generated by Django 3.1.1 on 2020-09-15 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0006_remove_leagues_country_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leagues',
            name='league_id',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='leagues',
            name='league_logo',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='leagues',
            name='league_name',
            field=models.CharField(max_length=20),
        ),
    ]
