# Generated by Django 3.1.1 on 2020-09-15 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0007_auto_20200915_1215'),
        ('leagues', '0007_auto_20200915_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leagues',
            name='country_id',
        ),
        migrations.AddField(
            model_name='leagues',
            name='country_league',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='countries.countries', verbose_name='Country'),
        ),
    ]
