# Generated by Django 3.1.1 on 2020-09-17 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='birthdate',
            field=models.DateField(blank=True, null=True, verbose_name='Established'),
        ),
        migrations.AlterField(
            model_name='team',
            name='league_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.league', verbose_name='League'),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_name',
            field=models.CharField(max_length=100, verbose_name='Team'),
        ),
    ]
