# Generated by Django 3.1.1 on 2020-09-09 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0002_auto_20200909_1354'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='countries',
            options={'verbose_name_plural': 'countries'},
        ),
    ]
