# Generated by Django 3.1.1 on 2020-09-11 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0005_countries_country_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countries',
            name='country_id',
            field=models.IntegerField(blank=True, default=90, null=True),
        ),
        migrations.AlterField(
            model_name='countries',
            name='country_logo',
            field=models.URLField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='countries',
            name='country_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
