# Generated by Django 3.1.1 on 2020-09-15 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0006_auto_20200911_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countries',
            name='country_logo',
            field=models.URLField(blank=True, default='EMPTY'),
        ),
    ]
