# Generated by Django 3.1.1 on 2020-09-15 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0007_auto_20200915_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countries',
            name='country_id',
            field=models.IntegerField(blank=True, default=90, null=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='countries',
            name='country_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Name'),
        ),
    ]
