# Generated by Django 3.1.1 on 2020-09-15 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0008_auto_20200915_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countries',
            name='country_logo',
            field=models.URLField(blank=True, default='EMPTY', verbose_name='Logo'),
        ),
    ]
