# Generated by Django 3.1.1 on 2020-09-08 11:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.IntegerField(default=90)),
                ('team_name', models.CharField(default=None, max_length=5)),
                ('date_now', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
