# Generated by Django 3.1.1 on 2020-09-15 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_lineups_matches_playersinteam_standings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teams',
            name='date_now',
        ),
    ]
