# Generated by Django 3.1.1 on 2020-09-15 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_auto_20200915_0822'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='country_id',
            field=models.IntegerField(blank=True, default=90, null=True),
        ),
    ]
