# Generated by Django 3.1.1 on 2020-09-15 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_teams_country_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='league_id',
            field=models.IntegerField(blank=True, default=4800),
        ),
    ]
