# Generated by Django 3.1.1 on 2020-09-15 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0008_auto_20200915_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='country_id',
            field=models.IntegerField(default=90, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='teams',
            name='league_id',
            field=models.IntegerField(blank=True, default=321, verbose_name='League'),
        ),
        migrations.AlterField(
            model_name='teams',
            name='team_badge',
            field=models.URLField(blank=True, verbose_name='Badge'),
        ),
        migrations.AlterField(
            model_name='teams',
            name='team_key',
            field=models.IntegerField(default=0, verbose_name='ID'),
        ),
    ]
