# Generated by Django 3.1.1 on 2020-09-15 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0009_auto_20200915_1522'),
        ('teams', '0009_auto_20200915_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teams',
            name='country_id',
        ),
        migrations.AddField(
            model_name='teams',
            name='country_team',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='countries.countries', verbose_name='Country'),
        ),
    ]
