# Generated by Django 3.1.1 on 2020-09-15 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0009_auto_20200915_1519'),
        ('countries', '0009_auto_20200915_1522'),
        ('teams', '0011_auto_20200915_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='country_team',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='countries.countries', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='teams',
            name='league_team',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leagues.leagues', verbose_name='League'),
        ),
    ]
